name: 'Dynatrace Workflow Ingester'
description: 'Ingests a workflow run into Grail'
author: 'Dynatrace'
inputs:
  dt-client-id:
    required: true
    description: 'Dynatrace Client ID'
  dt-client-secret:
    required: true
    description: 'Dynatrace Client Secret'
  dt-environment-id:
    required: true
    description: 'Dynatrace Environment ID'
  dt-resource:
    required: true
    description: 'Dynatrace Resource URN'
  dt-sso-url:
    required: false
    default: 'https://sso.dynatrace.com/sso/oauth2/token'
    description: 'Dynatrace SSO URL'

  debug:
    required: false
    default: 'false'
    description: 'Debug mode'
runs:
  using: 'node16'
  main: 'dist/index.js'
