{{- $values := .Values -}}
{{- $top := . -}}
{{- range $jobName, $job := $values.cronjobs }}
{{- if $job.enabled }}
{{- $defaultSyncWave := true }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "unified.name" $top }}-{{ $jobName }}
  labels:
    {{- include "unified.cronJobLabels" $top | nindent 4 }}
    app.kubernetes.io/component: {{ $jobName }}
  annotations:
    {{- if $job.metadata }}
    {{- with $job.metadata.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- if (index . "argocd.argoproj.io/sync-wave") }}
    {{- $defaultSyncWave = false }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if $defaultSyncWave }}
    # default sync wave for jobs
    argocd.argoproj.io/sync-wave: "-501"
    {{- end }}
spec:
  schedule: {{ required "$job.schedule is required" $job.schedule | quote }}
  {{- with $job.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with $job.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with $job.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with $job.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      {{- with $job.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      backoffLimit: {{ $job.backoffLimit | default 1 }}
      template:
        metadata:
          labels:
            {{- include "unified.jobLabels" $top | nindent 12 }}
            app.kubernetes.io/component: {{ $jobName }}
        {{- with $job.annotations }}
        annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        spec:
          {{- with $job.nodeSelector }}
          nodeSelector:
          {{ toYaml . | indent 2 }}
          {{- end }}
          {{- with $values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $values.externalSecret.enabled }}
          volumes:
            - name: vol-secret
              secret:
                secretName: {{ include "external-secret-unique-name" $ }}
          {{- end }}
          {{- with $job.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "unified.name" $top }}-{{ $jobName }}
              image: "{{ $values.image.repository }}:{{ $values.appVersion }}"
              imagePullPolicy: {{ $values.imagePullPolicy }}
              {{- if $values.externalSecret.enabled }}
              volumeMounts:
                {{- include "unified.externalsecret.volumemount" $ | nindent 16 }}
              {{- end }}
              {{- with $job.resources}}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
              {{- if $values.externalSecret.enabled }}
                - name: FRONTEGG_CONFIG_DIRECTORY
                  value: "/etc/config"
              {{- end }}
              {{- range $config_name, $values := $values.configuration.map }}
              {{- range $key, $value :=  $values}}
                - name: {{ $key }}
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $config_name }}
                      key: {{ $value }}
              {{- end }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "unified.name" $top }}-configmap
              command:
                {{- range .command }}
                - {{ . | quote  }}
                {{- end }}
              args:
                {{- range .args }}
                - {{ . | quote  }}
                {{- end }}
          {{- with $job.affinity }}
          affinity:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
          {{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy | default "Never" }}
{{- end }}
{{- end }}