{{- if .Values.hp.enabled }}
{{- if .Values.hp.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hp.name" . }}
spec:
  {{- with .Values.hp.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.hp.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hp.selector.labels" . | nindent 6 }}
      {{- if .Values.argoRollouts.enabled }}
      {{- if .Values.argoRollouts.progressiveDelivery.enabled }}
        {{- with .Values.argoRollouts.progressiveDelivery }}
        {{- toYaml .stableMetadata.labels | nindent 6 }}
        {{- end }}
      {{else}}      
        {{- with .Values.argoRollouts.activeMetadata }}
        {{- toYaml .labels | nindent 6 }}
      {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}